# frozen_string_literal: true

require_relative 'log'
require_relative 'config'
require_relative 'prompt_spec'
require_relative 'account_config'
require_relative 'account_block'
require_relative 'new_account'
require_relative 'detailer'
require_relative 'openai_client'
require_relative 'b2'
require_relative 'openai_error_reporter'
require_relative 'classifier'
require_relative 'converters/account_targets'
require_relative 'converters/base'
require_relative 'converters/amounts'
require_relative 'converters/default'
require_relative 'converters/cetes_directo'
require_relative 'converters/fintual'
require_relative 'converters/plata'
require_relative 'pipeline'
require_relative 'beancount_merger'
require_relative 'beancount/parser'
require_relative 'beancount/quoting'
require_relative 'beancount/header'
require_relative 'beancount/transaction'
require_relative 'beancount_detailer'
require_relative 'statement_rows'
require_relative 'statement'
require_relative 'ledger_repo'
require_relative 'reports'
require_relative 'ledger_edit'
require_relative 'period'

module Frijolero
end
