# frozen_string_literal: true

require_relative 'frijolero/version'
require_relative 'frijolero/ui'
require_relative 'frijolero/config'
require_relative 'frijolero/prompt_spec'
require_relative 'frijolero/account_config'
require_relative 'frijolero/accounts'
require_relative 'frijolero/detailer'
require_relative 'frijolero/openai_client'
require_relative 'frijolero/b2'
require_relative 'frijolero/openai_error_reporter'
require_relative 'frijolero/classifier'
require_relative 'frijolero/converters/account_targets'
require_relative 'frijolero/converters/base'
require_relative 'frijolero/converters/amounts'
require_relative 'frijolero/converters/beancount'
require_relative 'frijolero/converters/cetes_directo'
require_relative 'frijolero/converters/fintual'
require_relative 'frijolero/converters/plata'
require_relative 'frijolero/pipeline'
require_relative 'frijolero/beancount_merger'
require_relative 'frijolero/ledger_builder'
require_relative 'frijolero/pdf_uploader'
require_relative 'frijolero/beancount/parser'
require_relative 'frijolero/beancount/quoting'
require_relative 'frijolero/beancount/header'
require_relative 'frijolero/beancount/transaction'
require_relative 'frijolero/beancount_detailer'
require_relative 'frijolero/statement'

module Frijolero
end
